version: '3'

services:
  slackmirror:
    image: omercnet/slackmirror
    build: .
    environment:
      DEBUG:
      LOG_LEVEL: INFO
      PORT: 3000
      SLACK_SIGNING_SECRET: XXXX
      SLACK_BOT_TOKEN: xoxb-
      MIRROR_CHANNEL: general
      REDIS_URL: redis://redis
    ports:
      - 127.0.0.1:3000:3000
  redis:
    image: redis:8-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
    volumes:
      - .redis:/data
    ports:
      - 127.0.0.1:6379:6379
