version: '3'

services:
  slackmirror:
    image: omercnet/slackmirror
    build: .
    environment:
      DEBUG:
      LOG_LEVEL: INFO
      PORT: 3000
      SLACK_SIGNING_SECRET: XXXX
      SLACK_BOT_TOKEN: xoxb-
      MIRROR_CHANNEL: general
      REDIS_URL: redis://redis
    ports:
      - 127.0.0.1:3000:3000
  redis:
    image: redis:7-alpine
    volumes:
      - .redis:/data
    ports:
      - 127.0.0.1:6379:6379
